# Learn more about configuring your theme: https://shopify.dev/themes/tools/cli/configuration

[theme]
store = "humara-ghar.myshopify.com"
# theme_id = 142241824845  # Horizon (live theme)
# Current theme: Florasy - MultiPurpose Plant Store (Homepage 1)


